"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as alert_base_luma from "./styles/base-luma/alert";
import * as alert_base_lyra from "./styles/base-lyra/alert";
import * as alert_base_maia from "./styles/base-maia/alert";
import * as alert_base_mira from "./styles/base-mira/alert";
import * as alert_base_nova from "./styles/base-nova/alert";
import * as alert_base_rhea from "./styles/base-rhea/alert";
import * as alert_base_sera from "./styles/base-sera/alert";
import * as alert_base_vega from "./styles/base-vega/alert";
import * as alert_default from "./styles/default/alert";
import * as alert_new_york from "./styles/new-york/alert";

const MODULES = {
  "base-luma": alert_base_luma,
  "base-lyra": alert_base_lyra,
  "base-maia": alert_base_maia,
  "base-mira": alert_base_mira,
  "base-nova": alert_base_nova,
  "base-rhea": alert_base_rhea,
  "base-sera": alert_base_sera,
  "base-vega": alert_base_vega,
  "default": alert_default,
  "new-york": alert_new_york,
} as const;

export function Alert(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Alert ?? (alert_base_nova as any).Alert;
  return <Comp {...props} />;
}

export function AlertTitle(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).AlertTitle ?? (alert_base_nova as any).AlertTitle;
  return <Comp {...props} />;
}

export function AlertDescription(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).AlertDescription ?? (alert_base_nova as any).AlertDescription;
  return <Comp {...props} />;
}

export function AlertAction(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).AlertAction ?? (alert_base_nova as any).AlertAction;
  return <Comp {...props} />;
}
