"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as button_group_base_luma from "./styles/base-luma/button-group";
import * as button_group_base_lyra from "./styles/base-lyra/button-group";
import * as button_group_base_maia from "./styles/base-maia/button-group";
import * as button_group_base_mira from "./styles/base-mira/button-group";
import * as button_group_base_nova from "./styles/base-nova/button-group";
import * as button_group_base_rhea from "./styles/base-rhea/button-group";
import * as button_group_base_sera from "./styles/base-sera/button-group";
import * as button_group_base_vega from "./styles/base-vega/button-group";
import * as button_group_default from "./styles/default/button-group";
import * as button_group_new_york from "./styles/new-york/button-group";

const MODULES = {
  "base-luma": button_group_base_luma,
  "base-lyra": button_group_base_lyra,
  "base-maia": button_group_base_maia,
  "base-mira": button_group_base_mira,
  "base-nova": button_group_base_nova,
  "base-rhea": button_group_base_rhea,
  "base-sera": button_group_base_sera,
  "base-vega": button_group_base_vega,
  "default": button_group_default,
  "new-york": button_group_new_york,
} as const;

export function ButtonGroup(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ButtonGroup ?? (button_group_base_nova as any).ButtonGroup;
  return <Comp {...props} />;
}

export function ButtonGroupSeparator(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ButtonGroupSeparator ?? (button_group_base_nova as any).ButtonGroupSeparator;
  return <Comp {...props} />;
}

export function ButtonGroupText(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ButtonGroupText ?? (button_group_base_nova as any).ButtonGroupText;
  return <Comp {...props} />;
}

export { buttonGroupVariants } from "./styles/base-nova/button-group";
