"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as card_base_luma from "./styles/base-luma/card";
import * as card_base_lyra from "./styles/base-lyra/card";
import * as card_base_maia from "./styles/base-maia/card";
import * as card_base_mira from "./styles/base-mira/card";
import * as card_base_nova from "./styles/base-nova/card";
import * as card_base_rhea from "./styles/base-rhea/card";
import * as card_base_sera from "./styles/base-sera/card";
import * as card_base_vega from "./styles/base-vega/card";
import * as card_default from "./styles/default/card";
import * as card_new_york from "./styles/new-york/card";

const MODULES = {
  "base-luma": card_base_luma,
  "base-lyra": card_base_lyra,
  "base-maia": card_base_maia,
  "base-mira": card_base_mira,
  "base-nova": card_base_nova,
  "base-rhea": card_base_rhea,
  "base-sera": card_base_sera,
  "base-vega": card_base_vega,
  "default": card_default,
  "new-york": card_new_york,
} as const;

export function Card(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Card ?? (card_base_nova as any).Card;
  return <Comp {...props} />;
}

export function CardHeader(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).CardHeader ?? (card_base_nova as any).CardHeader;
  return <Comp {...props} />;
}

export function CardFooter(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).CardFooter ?? (card_base_nova as any).CardFooter;
  return <Comp {...props} />;
}

export function CardTitle(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).CardTitle ?? (card_base_nova as any).CardTitle;
  return <Comp {...props} />;
}

export function CardAction(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).CardAction ?? (card_base_nova as any).CardAction;
  return <Comp {...props} />;
}

export function CardDescription(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).CardDescription ?? (card_base_nova as any).CardDescription;
  return <Comp {...props} />;
}

export function CardContent(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).CardContent ?? (card_base_nova as any).CardContent;
  return <Comp {...props} />;
}
