"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as checkbox_base_luma from "./styles/base-luma/checkbox";
import * as checkbox_base_lyra from "./styles/base-lyra/checkbox";
import * as checkbox_base_maia from "./styles/base-maia/checkbox";
import * as checkbox_base_mira from "./styles/base-mira/checkbox";
import * as checkbox_base_nova from "./styles/base-nova/checkbox";
import * as checkbox_base_rhea from "./styles/base-rhea/checkbox";
import * as checkbox_base_sera from "./styles/base-sera/checkbox";
import * as checkbox_base_vega from "./styles/base-vega/checkbox";
import * as checkbox_default from "./styles/default/checkbox";
import * as checkbox_new_york from "./styles/new-york/checkbox";

const MODULES = {
  "base-luma": checkbox_base_luma,
  "base-lyra": checkbox_base_lyra,
  "base-maia": checkbox_base_maia,
  "base-mira": checkbox_base_mira,
  "base-nova": checkbox_base_nova,
  "base-rhea": checkbox_base_rhea,
  "base-sera": checkbox_base_sera,
  "base-vega": checkbox_base_vega,
  "default": checkbox_default,
  "new-york": checkbox_new_york,
} as const;

export function Checkbox(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Checkbox ?? (checkbox_base_nova as any).Checkbox;
  return <Comp {...props} />;
}
