"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
// default/new-york have no registry combobox; they reuse base-nova at runtime.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as combobox_base_luma from "./styles/base-luma/combobox";
import * as combobox_base_lyra from "./styles/base-lyra/combobox";
import * as combobox_base_maia from "./styles/base-maia/combobox";
import * as combobox_base_mira from "./styles/base-mira/combobox";
import * as combobox_base_nova from "./styles/base-nova/combobox";
import * as combobox_base_rhea from "./styles/base-rhea/combobox";
import * as combobox_base_sera from "./styles/base-sera/combobox";
import * as combobox_base_vega from "./styles/base-vega/combobox";

const MODULES = {
  "base-luma": combobox_base_luma,
  "base-lyra": combobox_base_lyra,
  "base-maia": combobox_base_maia,
  "base-mira": combobox_base_mira,
  "base-nova": combobox_base_nova,
  "base-rhea": combobox_base_rhea,
  "base-sera": combobox_base_sera,
  "base-vega": combobox_base_vega,
  "default": combobox_base_nova,
  "new-york": combobox_base_nova,
} as const;

export function Combobox(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Combobox ?? (combobox_base_nova as any).Combobox;
  return <Comp {...props} />;
}

export function ComboboxInput(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxInput ?? (combobox_base_nova as any).ComboboxInput;
  return <Comp {...props} />;
}

export function ComboboxContent(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxContent ?? (combobox_base_nova as any).ComboboxContent;
  return <Comp {...props} />;
}

export function ComboboxList(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxList ?? (combobox_base_nova as any).ComboboxList;
  return <Comp {...props} />;
}

export function ComboboxItem(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxItem ?? (combobox_base_nova as any).ComboboxItem;
  return <Comp {...props} />;
}

export function ComboboxGroup(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxGroup ?? (combobox_base_nova as any).ComboboxGroup;
  return <Comp {...props} />;
}

export function ComboboxLabel(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxLabel ?? (combobox_base_nova as any).ComboboxLabel;
  return <Comp {...props} />;
}

export function ComboboxCollection(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxCollection ?? (combobox_base_nova as any).ComboboxCollection;
  return <Comp {...props} />;
}

export function ComboboxEmpty(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxEmpty ?? (combobox_base_nova as any).ComboboxEmpty;
  return <Comp {...props} />;
}

export function ComboboxSeparator(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxSeparator ?? (combobox_base_nova as any).ComboboxSeparator;
  return <Comp {...props} />;
}

export function ComboboxChips(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxChips ?? (combobox_base_nova as any).ComboboxChips;
  return <Comp {...props} />;
}

export function ComboboxChip(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxChip ?? (combobox_base_nova as any).ComboboxChip;
  return <Comp {...props} />;
}

export function ComboboxChipsInput(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxChipsInput ?? (combobox_base_nova as any).ComboboxChipsInput;
  return <Comp {...props} />;
}

export function ComboboxTrigger(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxTrigger ?? (combobox_base_nova as any).ComboboxTrigger;
  return <Comp {...props} />;
}

export function ComboboxValue(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).ComboboxValue ?? (combobox_base_nova as any).ComboboxValue;
  return <Comp {...props} />;
}

export function useComboboxAnchor() {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  return (Mod.useComboboxAnchor ?? combobox_base_nova.useComboboxAnchor)();
}
