"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as field_base_luma from "./styles/base-luma/field";
import * as field_base_lyra from "./styles/base-lyra/field";
import * as field_base_maia from "./styles/base-maia/field";
import * as field_base_mira from "./styles/base-mira/field";
import * as field_base_nova from "./styles/base-nova/field";
import * as field_base_rhea from "./styles/base-rhea/field";
import * as field_base_sera from "./styles/base-sera/field";
import * as field_base_vega from "./styles/base-vega/field";
import * as field_default from "./styles/default/field";
import * as field_new_york from "./styles/new-york/field";

const MODULES = {
  "base-luma": field_base_luma,
  "base-lyra": field_base_lyra,
  "base-maia": field_base_maia,
  "base-mira": field_base_mira,
  "base-nova": field_base_nova,
  "base-rhea": field_base_rhea,
  "base-sera": field_base_sera,
  "base-vega": field_base_vega,
  "default": field_default,
  "new-york": field_new_york,
} as const;

export function Field(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Field ?? (field_base_nova as any).Field;
  return <Comp {...props} />;
}

export function FieldLabel(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldLabel ?? (field_base_nova as any).FieldLabel;
  return <Comp {...props} />;
}

export function FieldDescription(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldDescription ?? (field_base_nova as any).FieldDescription;
  return <Comp {...props} />;
}

export function FieldError(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldError ?? (field_base_nova as any).FieldError;
  return <Comp {...props} />;
}

export function FieldGroup(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldGroup ?? (field_base_nova as any).FieldGroup;
  return <Comp {...props} />;
}

export function FieldLegend(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldLegend ?? (field_base_nova as any).FieldLegend;
  return <Comp {...props} />;
}

export function FieldSeparator(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldSeparator ?? (field_base_nova as any).FieldSeparator;
  return <Comp {...props} />;
}

export function FieldSet(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldSet ?? (field_base_nova as any).FieldSet;
  return <Comp {...props} />;
}

export function FieldContent(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldContent ?? (field_base_nova as any).FieldContent;
  return <Comp {...props} />;
}

export function FieldTitle(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).FieldTitle ?? (field_base_nova as any).FieldTitle;
  return <Comp {...props} />;
}
