"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as label_base_luma from "./styles/base-luma/label";
import * as label_base_lyra from "./styles/base-lyra/label";
import * as label_base_maia from "./styles/base-maia/label";
import * as label_base_mira from "./styles/base-mira/label";
import * as label_base_nova from "./styles/base-nova/label";
import * as label_base_rhea from "./styles/base-rhea/label";
import * as label_base_sera from "./styles/base-sera/label";
import * as label_base_vega from "./styles/base-vega/label";
import * as label_default from "./styles/default/label";
import * as label_new_york from "./styles/new-york/label";

const MODULES = {
  "base-luma": label_base_luma,
  "base-lyra": label_base_lyra,
  "base-maia": label_base_maia,
  "base-mira": label_base_mira,
  "base-nova": label_base_nova,
  "base-rhea": label_base_rhea,
  "base-sera": label_base_sera,
  "base-vega": label_base_vega,
  "default": label_default,
  "new-york": label_new_york,
} as const;

export function Label(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Label ?? (label_base_nova as any).Label;
  return <Comp {...props} />;
}
