"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as radio_group_base_luma from "./styles/base-luma/radio-group";
import * as radio_group_base_lyra from "./styles/base-lyra/radio-group";
import * as radio_group_base_maia from "./styles/base-maia/radio-group";
import * as radio_group_base_mira from "./styles/base-mira/radio-group";
import * as radio_group_base_nova from "./styles/base-nova/radio-group";
import * as radio_group_base_rhea from "./styles/base-rhea/radio-group";
import * as radio_group_base_sera from "./styles/base-sera/radio-group";
import * as radio_group_base_vega from "./styles/base-vega/radio-group";
import * as radio_group_default from "./styles/default/radio-group";
import * as radio_group_new_york from "./styles/new-york/radio-group";

const MODULES = {
  "base-luma": radio_group_base_luma,
  "base-lyra": radio_group_base_lyra,
  "base-maia": radio_group_base_maia,
  "base-mira": radio_group_base_mira,
  "base-nova": radio_group_base_nova,
  "base-rhea": radio_group_base_rhea,
  "base-sera": radio_group_base_sera,
  "base-vega": radio_group_base_vega,
  "default": radio_group_default,
  "new-york": radio_group_new_york,
} as const;

export function RadioGroup(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).RadioGroup ?? (radio_group_base_nova as any).RadioGroup;
  return <Comp {...props} />;
}

export function RadioGroupItem(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).RadioGroupItem ?? (radio_group_base_nova as any).RadioGroupItem;
  return <Comp {...props} />;
}
