"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as switch_base_luma from "./styles/base-luma/switch";
import * as switch_base_lyra from "./styles/base-lyra/switch";
import * as switch_base_maia from "./styles/base-maia/switch";
import * as switch_base_mira from "./styles/base-mira/switch";
import * as switch_base_nova from "./styles/base-nova/switch";
import * as switch_base_rhea from "./styles/base-rhea/switch";
import * as switch_base_sera from "./styles/base-sera/switch";
import * as switch_base_vega from "./styles/base-vega/switch";
import * as switch_default from "./styles/default/switch";
import * as switch_new_york from "./styles/new-york/switch";

const MODULES = {
  "base-luma": switch_base_luma,
  "base-lyra": switch_base_lyra,
  "base-maia": switch_base_maia,
  "base-mira": switch_base_mira,
  "base-nova": switch_base_nova,
  "base-rhea": switch_base_rhea,
  "base-sera": switch_base_sera,
  "base-vega": switch_base_vega,
  "default": switch_default,
  "new-york": switch_new_york,
} as const;

export function Switch(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Switch ?? (switch_base_nova as any).Switch;
  return <Comp {...props} />;
}
