"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as table_base_luma from "./styles/base-luma/table";
import * as table_base_lyra from "./styles/base-lyra/table";
import * as table_base_maia from "./styles/base-maia/table";
import * as table_base_mira from "./styles/base-mira/table";
import * as table_base_nova from "./styles/base-nova/table";
import * as table_base_rhea from "./styles/base-rhea/table";
import * as table_base_sera from "./styles/base-sera/table";
import * as table_base_vega from "./styles/base-vega/table";
import * as table_default from "./styles/default/table";
import * as table_new_york from "./styles/new-york/table";

const MODULES = {
  "base-luma": table_base_luma,
  "base-lyra": table_base_lyra,
  "base-maia": table_base_maia,
  "base-mira": table_base_mira,
  "base-nova": table_base_nova,
  "base-rhea": table_base_rhea,
  "base-sera": table_base_sera,
  "base-vega": table_base_vega,
  "default": table_default,
  "new-york": table_new_york,
} as const;

export function Table(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Table ?? (table_base_nova as any).Table;
  return <Comp {...props} />;
}

export function TableHeader(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).TableHeader ?? (table_base_nova as any).TableHeader;
  return <Comp {...props} />;
}

export function TableBody(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).TableBody ?? (table_base_nova as any).TableBody;
  return <Comp {...props} />;
}

export function TableFooter(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).TableFooter ?? (table_base_nova as any).TableFooter;
  return <Comp {...props} />;
}

export function TableHead(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).TableHead ?? (table_base_nova as any).TableHead;
  return <Comp {...props} />;
}

export function TableRow(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).TableRow ?? (table_base_nova as any).TableRow;
  return <Comp {...props} />;
}

export function TableCell(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).TableCell ?? (table_base_nova as any).TableCell;
  return <Comp {...props} />;
}

export function TableCaption(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).TableCaption ?? (table_base_nova as any).TableCaption;
  return <Comp {...props} />;
}
