"use client";

// GLUE: auto-generated by scripts/install-ui.mjs — do not edit.
import * as React from "react";
import { useStyle } from "@/components/StyleProvider";
import * as textarea_base_luma from "./styles/base-luma/textarea";
import * as textarea_base_lyra from "./styles/base-lyra/textarea";
import * as textarea_base_maia from "./styles/base-maia/textarea";
import * as textarea_base_mira from "./styles/base-mira/textarea";
import * as textarea_base_nova from "./styles/base-nova/textarea";
import * as textarea_base_rhea from "./styles/base-rhea/textarea";
import * as textarea_base_sera from "./styles/base-sera/textarea";
import * as textarea_base_vega from "./styles/base-vega/textarea";
import * as textarea_default from "./styles/default/textarea";
import * as textarea_new_york from "./styles/new-york/textarea";

const MODULES = {
  "base-luma": textarea_base_luma,
  "base-lyra": textarea_base_lyra,
  "base-maia": textarea_base_maia,
  "base-mira": textarea_base_mira,
  "base-nova": textarea_base_nova,
  "base-rhea": textarea_base_rhea,
  "base-sera": textarea_base_sera,
  "base-vega": textarea_base_vega,
  "default": textarea_default,
  "new-york": textarea_new_york,
} as const;

export function Textarea(props: any) {
  const { style } = useStyle();
  const Mod = MODULES[style] ?? MODULES.default;
  const Comp = (Mod as any).Textarea ?? (textarea_base_nova as any).Textarea;
  return <Comp {...props} />;
}
